name: Backend CICD

on:
  push:
    branches:
    - main
    - staging
    tags:
    - 'v*'
  pull_request:
    branches:
    - 'main'
jobs:

  container-deploy:
    permissions:
      id-token: write
      contents: read
      actions: read
    runs-on: ubuntu-latest
    name: Deploy application to container instance
    env:
      # ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      # OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
      # OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
      # OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
      # OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
      # OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          ${{ secrets.DOCKER_REGISTRY }}/idhdwarejdxj/jph/cicd-test
        tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
    - name: Login to OCIR
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.DOCKER_REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
